/**
 * CRM Schema — LibSQL / Turso (SQLite dialect)
 *
 * ⚠️  This file is generated and managed by AIWA CRMx.
 *     Do not edit manually unless you know what you are doing.
 *
 * Generated by: Logic Architect Agent (claude-sonnet-4-5)
 * Dialect:      Turso / LibSQL (SQLite-compatible)
 *
 * Rules:
 * - All IDs are UUIDs stored as TEXT
 * - Timestamps are ISO strings stored as TEXT
 * - No DECIMAL — use TEXT for currency, INTEGER for whole-number cents
 * - Booleans stored as INTEGER (0 = false, 1 = true)
 */

import { text, integer, sqliteTable } from "drizzle-orm/sqlite-core";
import { sql, relations } from "drizzle-orm";

// ─── Utility ─────────────────────────────────────────────────────────────────

const timestamps = {
  createdAt: text("created_at")
    .notNull()
    .default(sql`(datetime('now'))`),
  updatedAt: text("updated_at")
    .notNull()
    .default(sql`(datetime('now'))`),
};

// ─── Users ────────────────────────────────────────────────────────────────────
// Internal CRM users (team members of the client company)

export const users = sqliteTable("users", {
  id: text("id")
    .primaryKey()
    .$defaultFn(() => crypto.randomUUID()),
  email: text("email").notNull().unique(),
  firstName: text("first_name").notNull(),
  lastName: text("last_name").notNull(),
  role: text("role", { enum: ["admin", "member", "viewer"] })
    .notNull()
    .default("member"),
  avatarUrl: text("avatar_url"),
  isActive: integer("is_active", { mode: "boolean" }).notNull().default(true),
  ...timestamps,
});

export type User = typeof users.$inferSelect;
export type NewUser = typeof users.$inferInsert;

// ─── Placeholder entities (replaced by Logic Architect) ──────────────────────
//
// The Logic Architect Agent will replace everything below this comment
// with entities derived from the approved CRM spec.
//
// Example entities it may generate:
//   contacts, companies, deals, pipelines,
//   tasks, tickets, notes, activities, tags
//
// ─────────────────────────────────────────────────────────────────────────────
