/**
 * CRM Schema — Neon (PostgreSQL dialect)
 *
 * ⚠️  This file is generated and managed by Falcon CRMx.
 *     Do not edit manually unless you know what you are doing.
 *
 * Generated by: Logic Architect Agent (claude-sonnet-4-5)
 * Dialect:      Neon / PostgreSQL
 *
 * Rules:
 * - All IDs are UUIDs using native PostgreSQL UUID type
 * - Timestamps use native PostgreSQL TIMESTAMP type
 * - No DECIMAL — use TEXT for currency, INTEGER for whole-number cents
 * - Booleans use native PostgreSQL BOOLEAN type
 */

import {
  pgTable,
  uuid,
  varchar,
  text,
  boolean,
  timestamp,
} from "drizzle-orm/pg-core";
import { relations } from "drizzle-orm";

// ─── Utility ─────────────────────────────────────────────────────────────────

const timestamps = {
  createdAt: timestamp("created_at").notNull().defaultNow(),
  updatedAt: timestamp("updated_at").notNull().defaultNow(),
};

// ─── Users ────────────────────────────────────────────────────────────────────
// Internal CRM users (team members of the client company)

export const users = pgTable("users", {
  id: uuid("id").primaryKey().defaultRandom(),
  email: varchar("email", { length: 255 }).notNull().unique(),
  firstName: varchar("first_name", { length: 100 }).notNull(),
  lastName: varchar("last_name", { length: 100 }).notNull(),
  role: varchar("role", { length: 50 }).notNull().default("member"),
  avatarUrl: text("avatar_url"),
  isActive: boolean("is_active").notNull().default(true),
  ...timestamps,
});

export type User = typeof users.$inferSelect;
export type NewUser = typeof users.$inferInsert;

// ─── Placeholder entities (replaced by Logic Architect) ──────────────────────
//
// The Logic Architect Agent will replace everything below this comment
// with entities derived from the approved CRM spec.
//
// Example entities it may generate:
//   contacts, companies, deals, pipelines,
//   tasks, tickets, notes, activities, tags
//
// ─────────────────────────────────────────────────────────────────────────────
